### ISSUE TITLE
Wiki von Github nutzen für Twee

### ISSUE THREAD

**Issue by humsp** [humsp/uebersetzerbauSWP#10]
Zusammenfassung von "Twine Index" aus http://twinery.org/wiki/

z.B.:
.tw datei beginnt mit
::PassageName    := name der Passage. Name muss eindeutig sein, da er für Links verwendet wird.

[[passageName]] := ist ein Link zu einer Passage.

**Comment by majdhasan** [comment]
Grammatik fehler : ein Link mit expression endet mit zwei 'BRACKET'  nicht einen !, 
Bsp : [[displayed text|title of passage][$variable = expression]]
