### ISSUE TITLE
Reguläre Definition für Twee-Lexer

### ISSUE THREAD

**Issue by humsp** [humsp/uebersetzerbauSWP#12]
Es soll eine Gruppenübergreifende reguläre Definition für alle Twee-Sprachelemente erstellt werden, welche die Tokens fomal spezifiziert. Die se muss komfom zu von Twee generierten .twee Files sein.

Tasks:
#20 
#29
#30
#31
#32

**Comment by humsp** [comment]
- Text format
- Funktionen
- Variablen
- Macros
- - print 
- - ...

**Comment by papierschiff** [comment]
ich bin vom rust team, vielleicht könnten wir uns da irgendwie abstimmen.
wir haben 2 pads dafür angelegt:
reg. definition: http://pad.spline.de/JkCJGPvrGB
kontextfr. grammatik: http://pad.spline.de/S1PvGRY99Q
