### ISSUE TITLE
Kontextfreie Grammatik für Twee-Parser

### ISSUE THREAD

**Issue by sungaila** [humsp/uebersetzerbauSWP#21]
Es soll eine Gruppenübergreifende reguläre Definition für alle (relevanten) Twee-Sprachelemente erstellt werden, welche die Tokens formal spezifiziert. Diese muss konform zu von Twine generierten .twee Files sein.

**Comment by sungaila** [comment]
Die anderen zwei Gruppen haben hierzu zwei sogenannte Etherpads erstellt.

http://pad.spline.de/JkCJGPvrGB
http://pad.spline.de/S1PvGRY99Q

**Comment by ThienLong93** [comment]
Muss die kontextfreie Grammatik nur die Sachen in Tokens zerlegen können oder auch irgendwelche Semantik verstehen?
Bsp:
Links -> [[passagen_Titel]]

Muss er jetzt überprüfen können ob die Passage existiert oder reich sowas aus?
