### ISSUE TITLE
Z-Code: Erzeuge Funktion die Text ausgibt

### ISSUE THREAD

**Issue by humsp** [humsp/uebersetzerbauSWP#35]
Kapitel 4:
https://kvv.imp.fu-berlin.de/access/content/group/3f18c297-eee1-4834-b068-8d051e87e95f/Referate/03-Z-Code/z-spec10.pdf

**Comment by sungaila** [comment]
#13 ist die dazugehörige Story

**Comment by DmitrijDy** [comment]
@sungaila ,hmmm...ich wollte den Task machen, folgendes Problem: wie?
Interface? Was soll rein, was soll raus? 
Ich würde es jetzt so verstehen:
static byte[] PrintText(string arr) -> kommt ein text rein als string, kommt ne bytearray raus mit [print <text>] als bytes kodiert für den z-code. Richtig so?
Also wir sollten glaub ich schon bei den Funktionen zumindest vereinbaren was rein kommt und was raus soll. Sonst erledigen wir alle Tasks, aber nichts passt zueinander.

**Comment by DmitrijDy** [comment]
app kann es sein, dass wenn wir in z8 arbeiten, dass es nix mehr mit 3 Buchstaben = 2 bytes ist? na ja weil soweit ich verstehe, sind 2 bytes ja 16 bits = 1vorbit + 3x5bits für Buchstaben => 2^5-1=31 Symbole können umgesetzt werden...also nicht mal groß/klein schreibung sondern wirklich nur 28 buchstaben. Aber z8 arbeitet ja mit groß/klein und sogar umlaute und so, sowiet ich das verstanden habe, also nix mit 5 bits pro Symbol, mit dem der Prof so geworben hat, oder sehe ich das falsch?

**Comment by humsp** [comment]
kannst du mal den Abschnitt verlinken wo das steht?

**Comment by humsp** [comment]
ich dachte es wäre in 3.3  so gemeint:
Man kann im string auch Abkürzungen codieren. Also wenn Texte häufiger vorkommen, dann man diese einfach refenrenzieren. Dieser referenzierte Text muss aber den 5 bits Text enthalten.

https://kvv.imp.fu-berlin.de/access/content/group/3f18c297-eee1-4834-b068-8d051e87e95f/Referate/03-Z-Code/z-spec10.pdf

**Comment by DmitrijDy** [comment]
hm, ok also wenn ich das dann richtig verstehe, dann muss man diese 5-bit zeug nicht unbedingt benutzen:
3.8.3
ZSCII codes between 32 ("space") and 126 ("tilde") are defined for input and output, and agreewith standard ASCII (as well as all of the ISO 8859 charactersets and Unicode). 
wäre cool, wenn mans ausprobieren könnte im Interpreter, aber ich glaube der wird's nicht vollen ohne drum herum, mal gucken.

**Comment by humsp** [comment]
Egal. Ich habe das Text zeug ist schon implementiert. Guck dir mal die Klasse ZText an.
