### ISSUE TITLE
Passage anpassen

### ISSUE THREAD

**Issue by humsp** [humsp/uebersetzerbauSWP#44]
Anpassen, dass die Gruppenübergreifende Grammatik akzeptiert wird.
Dafür das Gruppen.txt aus dem KVV ansehen.
Hier ein Auszug:

Passage (mindestens start passage)
  - Start der Datei ODER NEW_LINE
  - :: WHITESPACE*
  - PassageName:
    "normaler Text"
    EXPLIZIT ERLAUBT:	WHITESPACE, DOLLAR
    VERBOTEN:		PIPE, SQUARE_BRACKET, MACRO_BRACKET, DOPPELDOPPELPUNKT, NEW_LINE, führende und folgende WHITESPACE
    Vorerst keine Formatierung vom Text erlaubt
  - PassageTags:
    Geklammert mit [], getrennt von bel. vielen WHITESPACE
    Nur Buchstaben, Zahlen, Punkt, Unterstrich
  - Text zum Verwerfen
  - NEW_LINE
  - PassageContent

**Comment by ThienLong93** [comment]
Dollar sind nach den Datei nicht erlaubt!

**Comment by humsp** [comment]
Ich habe den Text Raubkopiert bevor dieser nochmal überarbeitet wurde.

**Comment by ThienLong93** [comment]
Aso :)
