### ISSUE TITLE
Grammatik um Function erweitern

### ISSUE THREAD

**Issue by humsp** [humsp/uebersetzerbauSWP#48]
Die Grammatik soll um functions erweitert werden.
Siehe Gruppendokument für Funktions.

Hier ein auszug:
Function
  - bestimmte Identifier
  - geklammert in ( )
  - enthält Expressions, separiert durch Komma
- Nur folgende Identifier unterstützt:
    - random
    - either
    - visited
    - visitedTag
    - turns
    - confirm
    - prompt

**Comment by ThienLong93** [comment]
Im Dokument steht, dass beliebige Fkt.Namen möglich sind.
