### ISSUE TITLE
Demo Twee Files

### ISSUE THREAD

**Issue by humsp** [humsp/uebersetzerbauSWP#51]
Wir benötigen Demo Twee files. Am Besten für jede Twee Funktion die wir unterstützen ein eigenesTwee File. Die Demo Files können auch aufeinanderaufbauend sein. Z.B. erst eins welches Variablen erstellt, dann eins welches Variablen verarbeitet (z.B. Variable incrementieren oder so.)
Dafür einen neuen Ordner im Projekt erstellen: "DemoTweeFiles". Damit alle Dateien aus diesem für Test genutzt werden können.
Am Besten die Gruppenübergreifende Definition durchgehen und anhand dieser die Files erstellen.

https://docs.google.com/document/d/11peEDqR6CCz4NCvLDIHKM0j6R_m_zju1aqesmizkXKI/edit

- Für jedes Kapitel sollten Demo Files erstellt werden.

- Jedes File sollte eindeutig benannt werden, sodass aus dem Titel auch der Inhalt ersichtlich ist. Dazu auch noch eine Kapitelkennzeichnung und Nummerierung im Namen. (z.B. "1.1_Pasagen name mit Sonderzeichen")

**Comment by ThienLong93** [comment]
Soll das hier auch assigned werden?
Und wenn ja an wen?^^

**Comment by humsp** [comment]
mir egal, irgendwen
